name: Swift

on:
  push:
    branches:
      - develop
    paths:
      - ".github/workflows/swift.yaml"
      - "**.swift"
      - "**/Package.resolved"
  pull_request:
    paths:
      - ".github/workflows/swift.yaml"
      - "**.swift"
      - "**/Package.resolved"

jobs:
  swiftformat:
    name: Check swiftformat
    runs-on: macOS-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Cache BuildTools/.build
        uses: actions/cache@v1
        with:
          path: BuildTools/.build
          key: ${{ runner.os }}-swift-tools-build-${{ hashFiles('BuildTools/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-swift-tools-build-
      - name: Cache ~/bin
        uses: actions/cache@v1
        with:
          path: ~/bin
          key: ${{ runner.os }}-home-bin-${{ hashFiles('BuildTools/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-home-bin-
      - name: Install Swift tools
        run: make swift-tools

      - name: Format Swift code
        run: swiftformat --verbose .

      - name: Verify formatted code is unchanged
        run: git diff --exit-code HEAD
