on:
  pull_request:
  push:
    branches:
      - "develop"

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: We test it locally with act
    steps:
      - name: Get Pokemon name
        uses: zea1ous/custom-github-action@main
        id: pokemon
        with:
          pokemon_id: 150
      - name: Get the pokemon
        run: echo "${{ steps.pokemon.outputs.pokemon_name }} attack"
        
      - name: Git Auto-commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply SwiftFormat changes
